
# About the Authors {-}

These credits are based on our [course contributors table guidelines](https://www.ottrproject.org/more_features.html#giving-credits-to-contributors).

&nbsp;
&nbsp;

|Credits|Names|
|-------|-----|
|**Pedagogy**||
|Lead Content Instructor(s)|[Candace Savonen]|
|Lecturer(s)|[Candace Savonen]|
|Content Contributor(s) | [Kate Isaac], [Carrie Wright] |
|Content Editor(s)/Reviewer(s) | [Carrie Wright], [Kate Isaac] |
|**Production**||
|Content Publisher(s)| [Carrie Wright], [Kate Isaac], [Candace Savonen]|
|Content Publishing Reviewer(s)| [Carrie Wright]|
|**Technical**||
|Course Publishing Engineer(s)| Helped with the code for the technical aspects related to the specific course generation|
|Template Publishing Engineers|[Candace Savonen], [Carrie Wright], [Ava Hoffman]|
|Publishing Maintenance Engineer|[Candace Savonen]|
|Technical Publishing Stylists|[Carrie Wright], [Ava Hoffman], [Candace Savonen]|
|Package Developers ([ottrpal])|[Candace Savonen], [Ava Hoffman], [Howard Baek], [Kate Isaac], [Carrie Wright], [John Muschelli]|
|**Art and Design**||
|Figure Artist(s)| [Carrie Wright], [Kate Isaac] |
|Videographer(s)| [Candace Savonen] |
|**Funding**||
|Funder|[National Cancer Institute (NCI)](https://www.cancer.gov/) UE5 CA254170|
|Funding Staff| [Allison Peters](https://www.linkedin.com/in/allisonrpeters/), [Maleah O'Connor](https://www.linkedin.com/in/maleah-o-connor/)|

&nbsp;

```{r, echo = FALSE}
devtools::session_info()
```

<!-- Author information -->

[John Muschelli]: https://johnmuschelli.com/
[Candace Savonen]: https://www.cansavvy.com/
[Carrie Wright]: https://carriewright11.github.io/
[Ava Hoffman]: https://www.avahoffman.com/
[Howard Baek]: https://www.linkedin.com/in/howard-baik/
[Kate Isaac]: https://kweav.github.io/

<!-- Links -->

[ottrpal]: https://github.com/ottrproject/ottrpal
